"""empty message

Revision ID: 3c3cc1bd88e2
Revises: None
Create Date: 2016-07-16 21:30:28.060230

"""

# revision identifiers, used by Alembic.
revision = '3c3cc1bd88e2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postings')
    ### end Alembic commands ###
